#!/usr/bin/env php
<?php
/**
 * APP Name:        Laika Framework Core
 * APP Provider:    Showket Ahmed
 * APP Link:        https://cloudbillmaster.com
 * APP Contact:     riyadtayf@gmail.com
 * APP Version:     1.0.0
 * APP Company:     Cloud Bill Master Ltd.
 */
use CBM\CoreHelper\Console\Console;

// Define Console Path
define('CONSOLEPATH', __DIR__);

if(PHP_SAPI !== 'cli'){
    echo 'Please Use Terminal for Console!';
    die;
}

require_once(CONSOLEPATH.'/vendor/autoload.php');

Console::run($argv);
